<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_Password123</name>
   <tag></tag>
   <elementGuidId>712b3207-27af-4f6e-8df3-9e1b87a168c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='login']/ul/li[2]/b[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>b:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>aaa7aaf5-f69b-418a-b0f4-a059be5428a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password123</value>
      <webElementGuid>12b0b8c7-3de9-4255-984a-4439e7201284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login&quot;)/ul[1]/li[2]/b[2]</value>
      <webElementGuid>5a122b07-0bfc-4f54-b460-92c011e38235</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='login']/ul/li[2]/b[2]</value>
      <webElementGuid>050decaa-df83-4bfd-9bfd-74664793946b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='student'])[1]/following::b[1]</value>
      <webElementGuid>507cfb45-c292-4f74-8fd3-80b0197c224f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/preceding::b[1]</value>
      <webElementGuid>e1e13c5f-ffa9-4ee3-ae4a-e784f4897bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::b[1]</value>
      <webElementGuid>653e2ecb-cbdb-49d8-8130-9165bee727bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Password123']/parent::*</value>
      <webElementGuid>6b953f2a-6cd3-4aab-90e0-659d8c38d901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b[2]</value>
      <webElementGuid>01c9ce51-e7be-45c2-9c46-0f5015a1858a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'Password123' or . = 'Password123')]</value>
      <webElementGuid>627f4275-8882-4ac7-8bc2-67a68f1cddec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
