<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Start Now</name>
   <tag></tag>
   <elementGuidId>81f2c7f3-d60b-4e81-8038-271dcedc73b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/section[4]/div/div/div/div/div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>09a47aa7-fa4f-45a2-852f-1c7ac4a329ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.lambdatest.com/certifications/selenium-101</value>
      <webElementGuid>0257971f-c110-4b69-bb43-0dd3f7a240ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-size-18 font-semibold text-black border border-black rounded hover:bg-black hover:text-white block text-center py-10 mt-50</value>
      <webElementGuid>9cbb7da4-0e09-4df2-b037-231323a91435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start Now</value>
      <webElementGuid>148a7669-a226-4141-89f8-a5edca8d6bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/section[@class=&quot;mt-70 mb-100&quot;]/div[@class=&quot;container__selenium&quot;]/div[@class=&quot;learn_main mt-50&quot;]/div[@class=&quot;columnhub px-15 xl:px-50 py-0 my-40 mx-0 grid grid-cols-3 gap-60 smtablet:block smtablet:w-full desktop:grid-cols-2 ipad:grid-cols-3 fromtablet:my-60 fromtablet:mx-0&quot;]/div[@class=&quot;border border-lambda-1200 rounded-xl pt-40 pb-27&quot;]/div[@class=&quot;px-22&quot;]/a[@class=&quot;text-size-18 font-semibold text-black border border-black rounded hover:bg-black hover:text-white block text-center py-10 mt-50&quot;]</value>
      <webElementGuid>90e72cfa-8e70-426d-9e6e-47e2ae396568</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/section[4]/div/div/div/div/div[3]/a</value>
      <webElementGuid>0b387866-19a4-43c2-ba6c-fd9219f14b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Start Now')]</value>
      <webElementGuid>b5331012-9c35-4f92-b307-579101225842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='beginner'])[1]/following::a[1]</value>
      <webElementGuid>15872882-5028-4036-9cf9-ec9f7038ec19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='advanced'])[1]/preceding::a[1]</value>
      <webElementGuid>be275f5e-10ca-42bc-ad5c-3aaab22030de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Start Now']/parent::*</value>
      <webElementGuid>f5242ae6-f366-4b40-a9c3-d79ee90078b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.lambdatest.com/certifications/selenium-101')]</value>
      <webElementGuid>8cf550d7-b4c4-4ada-a772-9e7411490a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>4484575e-591a-4d6f-a4b3-84b5c401b615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.lambdatest.com/certifications/selenium-101' and (text() = 'Start Now' or . = 'Start Now')]</value>
      <webElementGuid>28ee016e-7691-400f-b07a-54c67d429420</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
