<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Share_ytp-play-button ytp-button</name>
   <tag></tag>
   <elementGuidId>28d7dd14-ad0b-4155-a273-77eb2f526d39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#c4-player > div.ytp-chrome-bottom > div.ytp-chrome-controls > div.ytp-left-controls > button.ytp-play-button.ytp-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='c4-player']/div[28]/div[2]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a3d86fe4-74d9-4bb1-bcb0-1642cf84a533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ytp-play-button ytp-button</value>
      <webElementGuid>0a2f358d-4027-4a83-ba7c-e2ef5fd82ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-keyshortcuts</name>
      <type>Main</type>
      <value>k</value>
      <webElementGuid>9f961e53-3f21-40aa-bfa4-fbf9c138a146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title-no-tooltip</name>
      <type>Main</type>
      <value>Pause</value>
      <webElementGuid>802c8bbf-048a-4812-95b8-4c3bfad6c7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Pause keyboard shortcut k</value>
      <webElementGuid>c5dd9282-854e-49ab-96d4-55763f694ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c4-player&quot;)/div[@class=&quot;ytp-chrome-bottom&quot;]/div[@class=&quot;ytp-chrome-controls&quot;]/div[@class=&quot;ytp-left-controls&quot;]/button[@class=&quot;ytp-play-button ytp-button&quot;]</value>
      <webElementGuid>c906de77-d00b-4017-906d-8a2d21db67db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c4-player']/div[28]/div[2]/div/button</value>
      <webElementGuid>961015b4-c2e9-495c-b84f-8b34c2543caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share'])[4]/following::button[3]</value>
      <webElementGuid>bf269660-d0ac-4e9f-a348-c09b1f928213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Watch later'])[2]/following::button[4]</value>
      <webElementGuid>e9020e66-b108-472e-a656-954a041922dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[2]/preceding::button[2]</value>
      <webElementGuid>7d9cdf4c-6c36-448c-97e2-1b6b8f06074a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='•'])[67]/preceding::button[2]</value>
      <webElementGuid>4c8ece68-dee2-4f6b-8016-e759f701b977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[28]/div[2]/div/button</value>
      <webElementGuid>f0f8b62c-dbd1-4213-97db-80155df89a88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
