<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search for_s</name>
   <tag></tag>
   <elementGuidId>c7e6e772-7d68-43af-9f48-e7686815a299</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='s']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;s&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3dff16fd-d8ef-41ec-a413-3a4c831f8010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>94625dde-9a9e-4fe1-b627-28365e1ae7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-field</value>
      <webElementGuid>62b835da-a231-45e6-9e9d-d2724c3a6b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search …</value>
      <webElementGuid>3674b3a9-f52c-4463-93f9-1a69a6128cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>616599f8-4fef-4397-837c-ad2c74648bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;archive category category-automation category-2 sidebar userloggedOut hasSitekit&quot;]/section[@class=&quot;blog-sec&quot;]/div[@class=&quot;container-fluid blog-banner-head&quot;]/div[2]/form[@class=&quot;search-form&quot;]/label[1]/input[@class=&quot;search-field&quot;]</value>
      <webElementGuid>c14761ad-f9ce-4bbe-9741-e52431c7a8c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='s']</value>
      <webElementGuid>a37d8577-a2c6-44c8-8d2a-ffddeae8d168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2f6cfffd-10b1-4877-9099-a0bf6981168e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @placeholder = 'Search …' and @name = 's']</value>
      <webElementGuid>ef1d5164-edf4-4540-bfbf-2ad84cfe1cd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
