<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Selenium</name>
   <tag></tag>
   <elementGuidId>d8858b05-90f0-4eb8-853f-69e2627f5573</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-item-89 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-89']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d5275bae-6708-449b-a266-03577535e23d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://automationstepbystep.com/selenium/</value>
      <webElementGuid>2fa51b1c-50fc-4e45-b1c3-7dc5a7fe9b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selenium</value>
      <webElementGuid>4d7d8960-63eb-415a-93ad-5c4006bce098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-89&quot;)/a[1]</value>
      <webElementGuid>df6163e1-4e6e-447d-83cf-f75db2f6aa1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-89']/a</value>
      <webElementGuid>96535c99-51b3-417f-b139-d41a81d00d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Selenium')]</value>
      <webElementGuid>eb838b5e-0824-467e-848a-5a6848604adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JMeter Advanced'])[1]/following::a[1]</value>
      <webElementGuid>1b22eaa5-c779-4aee-8cda-a83623527ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JMeter Intermediate'])[1]/following::a[2]</value>
      <webElementGuid>d5677a6e-ed7e-4739-84c1-45cf23b865c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selenium Introduction'])[1]/preceding::a[1]</value>
      <webElementGuid>18213384-c5f4-4fb4-a5df-67df45d53db1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selenium TIPS'])[1]/preceding::a[2]</value>
      <webElementGuid>c1196ca9-8c7f-4d2f-a9e6-908ab2c00a5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selenium']/parent::*</value>
      <webElementGuid>e403d51b-1591-4dc9-a0e2-fd1cbed15558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://automationstepbystep.com/selenium/')]</value>
      <webElementGuid>958badba-6840-4bbd-be3e-27f2adc0290c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>22759592-52ec-4234-9df4-0abfbc2ddcaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://automationstepbystep.com/selenium/' and (text() = 'Selenium' or . = 'Selenium')]</value>
      <webElementGuid>58da0f46-3a08-4814-9ac4-5d608440cbcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
