<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Automation</name>
   <tag></tag>
   <elementGuidId>9a1a1043-d999-4f58-b8f1-078765ecbb56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-43']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-43 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ac5b58f2-151d-4e6a-86f7-98d1c16ef9fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.lambdatest.com/blog/category/automation/</value>
      <webElementGuid>07ef690d-abd8-472a-a374-bd004fd05106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automation</value>
      <webElementGuid>9441d6cb-5752-4cb4-a2a2-e9f798d049c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-43&quot;)/a[1]</value>
      <webElementGuid>d4e5998c-bd51-4fdf-9234-60ac0b3c9d00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-43']/a</value>
      <webElementGuid>c7d0c449-1650-494c-abc3-f233ebd12b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Automation')])[2]</value>
      <webElementGuid>9156c9f6-6a4e-4a37-8f24-a8c802dd5573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categories'])[1]/following::a[1]</value>
      <webElementGuid>34b9337c-e051-480a-8c2a-8ec6b2127bf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last »'])[1]/following::a[1]</value>
      <webElementGuid>76715bfa-585a-45e5-a463-4af1d1bf5d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HyperExecute'])[2]/preceding::a[1]</value>
      <webElementGuid>9d28000a-160f-4369-9ab6-290ac5b1fadc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thought Leadership'])[3]/preceding::a[2]</value>
      <webElementGuid>356111c2-71d4-49ea-8702-1465ac076fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.lambdatest.com/blog/category/automation/')])[2]</value>
      <webElementGuid>90939ca7-d1f6-400c-8456-50bc05dd6d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div/ul/li/a</value>
      <webElementGuid>7cf9d4e8-8e31-4f74-a668-18704cb43811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.lambdatest.com/blog/category/automation/' and (text() = 'Automation' or . = 'Automation')]</value>
      <webElementGuid>d58268e9-85cf-42b3-ae19-ba2547694e48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
