<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Selenium_alignnone  wp-image-940 (1)</name>
   <tag></tag>
   <elementGuidId>40b26796-b2ef-4432-bc1f-a2cd48333727</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.alignnone.wp-image-940</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='pageid-88']/div/div[2]/p/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>32d5882c-5638-46c2-b493-402b168b2568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>14a3f045-657a-4df8-84ed-969dcbd6b7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attachment-id</name>
      <type>Main</type>
      <value>940</value>
      <webElementGuid>6df67f79-315a-4a78-bb6f-f0edb6978234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-permalink</name>
      <type>Main</type>
      <value>https://automationstepbystep.com/ui-testing/screen-shot-2018-09-11-at-1-58-13-pm/</value>
      <webElementGuid>8f195bc9-f4f8-401f-87de-bb8cac07ff1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orig-file</name>
      <type>Main</type>
      <value>https://i1.wp.com/automationstepbystep.com/mobufoc/2018/09/Screen-Shot-2018-09-11-at-1.58.13-PM.png?fit=1656%2C934&amp;ssl=1</value>
      <webElementGuid>8fb719b4-29e3-487a-a32a-a2abcc9b2dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orig-size</name>
      <type>Main</type>
      <value>1656,934</value>
      <webElementGuid>88e18a9b-79fe-4e6d-897e-acd181544d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-comments-opened</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>375cabdd-cab9-4259-9d4a-7c799fb3dd2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-meta</name>
      <type>Main</type>
      <value>{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}</value>
      <webElementGuid>855594b8-4bcd-46d9-84bd-1d19257e8454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-title</name>
      <type>Main</type>
      <value>Screen Shot 2018-09-11 at 1.58.13 PM</value>
      <webElementGuid>463659bf-0a5f-4a0f-8beb-e4fbdf8d3df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-medium-file</name>
      <type>Main</type>
      <value>https://i1.wp.com/automationstepbystep.com/mobufoc/2018/09/Screen-Shot-2018-09-11-at-1.58.13-PM.png?fit=300%2C169&amp;ssl=1</value>
      <webElementGuid>e44f5a0d-1e69-4354-a768-1faf21d84f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-large-file</name>
      <type>Main</type>
      <value>https://i1.wp.com/automationstepbystep.com/mobufoc/2018/09/Screen-Shot-2018-09-11-at-1.58.13-PM.png?fit=1024%2C578&amp;ssl=1</value>
      <webElementGuid>579e00e6-aa87-4096-8864-e9cf42564d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alignnone  wp-image-940</value>
      <webElementGuid>72dfc0d6-a0a7-4e0f-bdef-d4bd56856393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://i0.wp.com/automationstepbystep.com/mobufoc/2018/09/Screen-Shot-2018-09-11-at-1.58.13-PM-300x169.png?resize=160%2C90</value>
      <webElementGuid>7fa2e6c5-ac7f-466f-897a-42ceb781aca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://i1.wp.com/automationstepbystep.com/mobufoc/2018/09/Screen-Shot-2018-09-11-at-1.58.13-PM.png?resize=300%2C169&amp;ssl=1 300w, https://i1.wp.com/automationstepbystep.com/mobufoc/2018/09/Screen-Shot-2018-09-11-at-1.58.13-PM.png?resize=768%2C433&amp;ssl=1 768w, https://i1.wp.com/automationstepbystep.com/mobufoc/2018/09/Screen-Shot-2018-09-11-at-1.58.13-PM.png?resize=1024%2C578&amp;ssl=1 1024w, https://i1.wp.com/automationstepbystep.com/mobufoc/2018/09/Screen-Shot-2018-09-11-at-1.58.13-PM.png?w=1656&amp;ssl=1 1656w</value>
      <webElementGuid>b3d701c2-1e50-44e2-8b54-6c0c93d71263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 160px) 100vw, 160px</value>
      <webElementGuid>0c4c57ca-f252-4020-bfd4-ccc4d2025d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>160</value>
      <webElementGuid>501e6390-53c7-45a1-b2e9-4bc3bf0fe38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>7f403a82-a997-4454-99ac-d7dca060e5cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pageid-88&quot;)/div[@class=&quot;entry-box clearfix&quot;]/div[@class=&quot;entry&quot;]/p[1]/a[1]/img[@class=&quot;alignnone  wp-image-940&quot;]</value>
      <webElementGuid>39983770-9268-4a5b-806f-d6adefe4d64e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='pageid-88']/div/div[2]/p/a/img</value>
      <webElementGuid>49125387-35c9-41e8-9e5e-604fcb90e0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://i0.wp.com/automationstepbystep.com/mobufoc/2018/09/Screen-Shot-2018-09-11-at-1.58.13-PM-300x169.png?resize=160%2C90')]</value>
      <webElementGuid>8fc9afb9-0118-4784-ac94-7628574013d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>a6feb456-b204-4314-aeb2-adb67903f1d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://i0.wp.com/automationstepbystep.com/mobufoc/2018/09/Screen-Shot-2018-09-11-at-1.58.13-PM-300x169.png?resize=160%2C90']</value>
      <webElementGuid>8a398eef-ea9d-427b-b3a2-b24a43fe50be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
