<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Selenium_alignnone  wp-image-940</name>
   <tag></tag>
   <elementGuidId>9c25b9aa-3a88-4c03-bc75-ceaa33c2593a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.alignnone.wp-image-940</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='pageid-88']/div/div[2]/p/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e7592c79-cde1-4684-b287-cdce0139c95b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>5ddd33c9-61f8-42f9-a1f4-6ad08dc4d0e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attachment-id</name>
      <type>Main</type>
      <value>940</value>
      <webElementGuid>483b5e58-4e23-4ede-84ae-cb9c9479b26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-permalink</name>
      <type>Main</type>
      <value>https://automationstepbystep.com/ui-testing/screen-shot-2018-09-11-at-1-58-13-pm/</value>
      <webElementGuid>bb63d298-c5a7-4697-acc6-d32f26ae774a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orig-file</name>
      <type>Main</type>
      <value>https://i1.wp.com/automationstepbystep.com/mobufoc/2018/09/Screen-Shot-2018-09-11-at-1.58.13-PM.png?fit=1656%2C934&amp;ssl=1</value>
      <webElementGuid>4d6964f4-b238-41b6-851d-7dc27965225e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orig-size</name>
      <type>Main</type>
      <value>1656,934</value>
      <webElementGuid>12135df4-33ad-4d99-a79f-5e05ec80fc78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-comments-opened</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>71c56951-b464-424d-845e-063a56230a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-meta</name>
      <type>Main</type>
      <value>{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}</value>
      <webElementGuid>189c8cc7-d73f-4013-a7f1-49940a949568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-title</name>
      <type>Main</type>
      <value>Screen Shot 2018-09-11 at 1.58.13 PM</value>
      <webElementGuid>bc3f9c1f-fb97-4a9f-96d9-0f4967f9a622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-medium-file</name>
      <type>Main</type>
      <value>https://i1.wp.com/automationstepbystep.com/mobufoc/2018/09/Screen-Shot-2018-09-11-at-1.58.13-PM.png?fit=300%2C169&amp;ssl=1</value>
      <webElementGuid>2ea5361e-1691-4a66-a0b0-3ef4c39d34a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-large-file</name>
      <type>Main</type>
      <value>https://i1.wp.com/automationstepbystep.com/mobufoc/2018/09/Screen-Shot-2018-09-11-at-1.58.13-PM.png?fit=1024%2C578&amp;ssl=1</value>
      <webElementGuid>ae98b7ec-3a3d-4298-973b-f795a846a5ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alignnone  wp-image-940</value>
      <webElementGuid>981958e5-7882-45a1-a3cf-6aabc202f7b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://i0.wp.com/automationstepbystep.com/mobufoc/2018/09/Screen-Shot-2018-09-11-at-1.58.13-PM-300x169.png?resize=160%2C90</value>
      <webElementGuid>e26078b3-66e3-45f2-8764-afba80647d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://i1.wp.com/automationstepbystep.com/mobufoc/2018/09/Screen-Shot-2018-09-11-at-1.58.13-PM.png?resize=300%2C169&amp;ssl=1 300w, https://i1.wp.com/automationstepbystep.com/mobufoc/2018/09/Screen-Shot-2018-09-11-at-1.58.13-PM.png?resize=768%2C433&amp;ssl=1 768w, https://i1.wp.com/automationstepbystep.com/mobufoc/2018/09/Screen-Shot-2018-09-11-at-1.58.13-PM.png?resize=1024%2C578&amp;ssl=1 1024w, https://i1.wp.com/automationstepbystep.com/mobufoc/2018/09/Screen-Shot-2018-09-11-at-1.58.13-PM.png?w=1656&amp;ssl=1 1656w</value>
      <webElementGuid>99150f03-6f75-4294-9f9b-088d8ce15af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 160px) 100vw, 160px</value>
      <webElementGuid>a47621de-1566-45f1-aa7e-0b150556f00e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>160</value>
      <webElementGuid>d7c2f833-37ca-452b-86f1-9c130b578b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>79bed2bd-4c31-4458-92a8-e08bdd41ecd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pageid-88&quot;)/div[@class=&quot;entry-box clearfix&quot;]/div[@class=&quot;entry&quot;]/p[1]/a[1]/img[@class=&quot;alignnone  wp-image-940&quot;]</value>
      <webElementGuid>209ba478-7960-436c-8318-0bc21a944574</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='pageid-88']/div/div[2]/p/a/img</value>
      <webElementGuid>50c914f9-416e-4b34-ac61-fc01f34c9126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://i0.wp.com/automationstepbystep.com/mobufoc/2018/09/Screen-Shot-2018-09-11-at-1.58.13-PM-300x169.png?resize=160%2C90')]</value>
      <webElementGuid>e41e946b-ed5d-45f1-92a3-02da39286498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>ccc81909-a9ce-4e77-a425-d4adbe23554e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://i0.wp.com/automationstepbystep.com/mobufoc/2018/09/Screen-Shot-2018-09-11-at-1.58.13-PM-300x169.png?resize=160%2C90']</value>
      <webElementGuid>9dd3113f-2fac-4308-8018-a9d8d18435f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
