<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Java</name>
   <tag></tag>
   <elementGuidId>c52a9522-0904-4ee2-93ab-7802857ea70d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__docusaurus_skipToContent_fallback']/div/main/div/div/div/div/article/div[2]/div/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.lt_primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e0be98f7-6198-4d20-8262-0ba4358751ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lt_primary</value>
      <webElementGuid>aef347eb-4465-46ad-b877-5d6bb2abd554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/support/docs/java-with-selenium-running-java-automation-scripts-on-lambdatest-selenium-grid/</value>
      <webElementGuid>3531f3a5-aa7f-4fce-86b1-3707fbb31941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Java</value>
      <webElementGuid>f03d969b-4770-4c80-a184-d46ab62d705a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__docusaurus_skipToContent_fallback&quot;)/div[@class=&quot;docPage__5DB&quot;]/main[@class=&quot;docMainContainer_gTbr&quot;]/div[@class=&quot;container padding-top--md padding-bottom--lg&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col docItemCol_VOVn&quot;]/div[@class=&quot;docItemContainer_Djhp&quot;]/article[1]/div[@class=&quot;theme-doc-markdown markdown&quot;]/div[@class=&quot;lt_row lt_framework_list_row&quot;]/div[@class=&quot;lt_col lt_framework_wrapper&quot;]/ul[@class=&quot;lt_framework_list&quot;]/li[1]/a[@class=&quot;lt_primary&quot;]</value>
      <webElementGuid>5094a738-1980-44f2-a59b-eaf5df8eb92d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__docusaurus_skipToContent_fallback']/div/main/div/div/div/div/article/div[2]/div/div/ul/li/a</value>
      <webElementGuid>9212c45a-fe6b-4d3e-8a4e-fb98e0e37623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Java')]</value>
      <webElementGuid>cae04017-1732-49c1-a5a0-0bd9320bcde7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/following::a[1]</value>
      <webElementGuid>a5e97613-1f74-46d6-967d-c21a914ebe2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selenide'])[1]/preceding::a[1]</value>
      <webElementGuid>49010cde-c60e-477d-8388-12fba08cc2d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gauge'])[1]/preceding::a[2]</value>
      <webElementGuid>6714c55b-baca-43ba-902c-499b0eb7b5f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Java']/parent::*</value>
      <webElementGuid>7738094c-a64d-4b80-bc02-18a28cec8717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/support/docs/java-with-selenium-running-java-automation-scripts-on-lambdatest-selenium-grid/')]</value>
      <webElementGuid>94af460e-a387-466a-9413-7da6cfd3d83c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li/a</value>
      <webElementGuid>b2566223-e451-49be-b064-bf97adfd0fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/support/docs/java-with-selenium-running-java-automation-scripts-on-lambdatest-selenium-grid/' and (text() = 'Java' or . = 'Java')]</value>
      <webElementGuid>34a66a42-0ece-4687-83e0-8f5ab173e1c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
