<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Sample for creating own test case object manually</description>
   <name>Sample_25</name>
   <tag></tag>
   <elementGuidId>a15b55ff-e1da-41a8-bfd5-1d16dd2a6e07</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id=&quot;inputFirstName&quot;]
</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
