<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Default value 15_sp__range</name>
   <tag></tag>
   <elementGuidId>5fbcda34-7edb-4905-89ca-0400eb873034</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sp__range.sp__range-success > input.sp__range</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='15']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>444689ac-f59b-4122-a384-712c5d2ec0a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>range</value>
      <webElementGuid>7ca53e96-cdbb-4443-b703-c22b4164be89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sp__range</value>
      <webElementGuid>795a1c1c-9ef2-4ef1-88ad-1d32d19e046e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>56d6e443-f7c4-4c53-b6fb-2c02bbcaa4c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>a6a47ea9-c79f-44bc-9168-79139cd2f2a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>66c7fe11-dd00-448c-a4c9-25f70aed8641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slider3&quot;)/div[@class=&quot;sp__range sp__range-success&quot;]/input[@class=&quot;sp__range&quot;]</value>
      <webElementGuid>a38e64a3-a340-4626-9978-3876d19fe503</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='15']</value>
      <webElementGuid>19cdf269-ecf0-44d8-8062-ea79dcfb8f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slider3']/div/input</value>
      <webElementGuid>f50aac6c-9284-49ab-af0d-411f44c4b9e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>cddb1064-cfc5-4a59-a48b-7206d9914039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'range']</value>
      <webElementGuid>f4150167-57fa-4745-a8bc-818805b72761</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
