<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>output_1</name>
   <tag></tag>
   <elementGuidId>90e7315a-eb9d-4d24-aa1c-002bc9717fda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//output[@id='rangeInfo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rangeInfo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>output</value>
      <webElementGuid>579578a1-c72a-42f2-a189-77028686eca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rangeInfo</value>
      <webElementGuid>06f10281-a082-42ba-a657-b1f27130790e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>77f5b6ed-84f3-4dba-8782-db61669d7697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rangeInfo&quot;)</value>
      <webElementGuid>fc19fe12-8640-41de-a61f-e272b21c662a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//output[@id='rangeInfo']</value>
      <webElementGuid>a514f57e-7634-4d60-93f8-26ea5329e286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slider4']/div/output</value>
      <webElementGuid>41913169-8c6b-414e-b0bf-4befb10dd303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 50'])[1]/following::output[1]</value>
      <webElementGuid>d3dea44f-f0fb-4d2b-a0fd-c4589c9c1595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 15'])[1]/following::output[2]</value>
      <webElementGuid>c0900ea5-b969-4db9-8f66-b47fd103dc2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 25'])[1]/preceding::output[1]</value>
      <webElementGuid>41abe0ec-2a8f-4cfc-939d-5065837108ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 30'])[1]/preceding::output[2]</value>
      <webElementGuid>e364eb69-145e-4e94-a508-0b61a9c7f00a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1']/parent::*</value>
      <webElementGuid>345d0a21-b525-48fd-9c8c-749a6cf27402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/output</value>
      <webElementGuid>8f1e380a-c101-4c73-b45d-18a4270edd85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//output[@id = 'rangeInfo' and (text() = '1' or . = '1')]</value>
      <webElementGuid>bcc9a734-35c6-4cbf-95e7-e8f39d6b9496</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
