<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>output_98</name>
   <tag></tag>
   <elementGuidId>3d12f4dd-d383-4bb8-a9f8-4f9b3bcd7bfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#slider7 > div.sp__range.sp__range-warning > #rangeWarning</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//output[@id='rangeWarning'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>output</value>
      <webElementGuid>d91bf398-bf90-498e-b3f7-efadd8f1f3ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rangeWarning</value>
      <webElementGuid>c5b0fdf4-81f2-4e5a-90cb-9e1426ecec39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>98</value>
      <webElementGuid>7f2f3755-e8c9-4076-a3bd-4912cac14d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slider7&quot;)/div[@class=&quot;sp__range sp__range-warning&quot;]/output[@id=&quot;rangeWarning&quot;]</value>
      <webElementGuid>9c2de0ac-8935-4576-b723-2df1eb3a7951</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//output[@id='rangeWarning'])[2]</value>
      <webElementGuid>8e39646a-05d2-450d-8173-32548bb9c00a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slider7']/div/output</value>
      <webElementGuid>6a5ba666-6380-4e84-9d46-10c51c0c396a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 40'])[1]/following::output[1]</value>
      <webElementGuid>c53f8d6f-442e-4bd8-902e-36d1057f1f8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 30'])[1]/following::output[2]</value>
      <webElementGuid>71de206a-6cbe-46c3-8fa0-6a7e2828a7d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 80'])[1]/preceding::output[1]</value>
      <webElementGuid>aec63fc8-3dcb-4564-b4b0-28607f649f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Testing'])[1]/preceding::output[2]</value>
      <webElementGuid>36be9bdf-d85d-4dc6-87d0-fb976906c79c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='98']/parent::*</value>
      <webElementGuid>70c54852-3c97-4ced-880d-48b3e358a463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/output</value>
      <webElementGuid>5ae59f86-9f64-4f1b-bccc-233d071a5866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//output[@id = 'rangeWarning' and (text() = '98' or . = '98')]</value>
      <webElementGuid>c558241e-ed76-4ec3-b28e-96321b0bdcfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
