<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>output_91_1</name>
   <tag></tag>
   <elementGuidId>5e8fe696-5a75-43d2-aeee-73c92cae2f3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//output[@id='rangePrimary']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rangePrimary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>output</value>
      <webElementGuid>3ed9ad3a-da26-445d-ac79-62781f0b07f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rangePrimary</value>
      <webElementGuid>887c1b9b-f65b-4771-a035-d6c36273cb32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>91</value>
      <webElementGuid>e5963748-f324-4692-90d2-68b4d7c2e415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rangePrimary&quot;)</value>
      <webElementGuid>b84f00e9-3aa0-4ae4-b822-9175d777aef2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//output[@id='rangePrimary']</value>
      <webElementGuid>33f7a6e6-e615-4930-a579-68dbc138e963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slider2']/div/output</value>
      <webElementGuid>6d1993a3-f847-4198-a399-e8b03a066683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 20'])[1]/following::output[1]</value>
      <webElementGuid>67e6c98d-e0e6-4c80-aa64-4a3c91c78c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 5'])[1]/following::output[2]</value>
      <webElementGuid>acb8fa10-0af1-44bc-8819-ebf5c83942af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 15'])[1]/preceding::output[1]</value>
      <webElementGuid>dce46dc1-38ff-44d1-81be-454b787d04b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 50'])[1]/preceding::output[2]</value>
      <webElementGuid>8c873877-fcd3-4827-869b-60fecb275a1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='91']/parent::*</value>
      <webElementGuid>470c4593-76b3-45f3-826a-39e4fb5114f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/output</value>
      <webElementGuid>be69c0fe-34a2-43de-b4aa-c0066ae01ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//output[@id = 'rangePrimary' and (text() = '91' or . = '91')]</value>
      <webElementGuid>9c18aed6-c527-420d-823d-33233bd1298a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
