<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>output_95</name>
   <tag></tag>
   <elementGuidId>a93b5b6a-9a17-41f1-ab16-71728f0ccc22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rangeSuccess</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//output[@id='rangeSuccess']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>output</value>
      <webElementGuid>b431b5b8-13ab-4fb1-bb6f-c152173a2ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rangeSuccess</value>
      <webElementGuid>24b558ad-3bc3-48fd-b004-fd71eb8bb898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>95</value>
      <webElementGuid>e3b9856b-8a4d-4a24-aa49-22e1795f6897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rangeSuccess&quot;)</value>
      <webElementGuid>4d9bb207-373b-45d9-aca7-6ded18438d89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//output[@id='rangeSuccess']</value>
      <webElementGuid>a9cea4f9-52d1-47a1-a907-3288d23e5920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slider3']/div/output</value>
      <webElementGuid>049fb363-2280-48ef-a0f7-8a1d1de86857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 15'])[1]/following::output[1]</value>
      <webElementGuid>77938f1a-0809-4b7b-b046-7ae2b77e919f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 20'])[1]/following::output[2]</value>
      <webElementGuid>0b05a604-c75c-4815-bc97-072afd027b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 50'])[1]/preceding::output[1]</value>
      <webElementGuid>854e5d68-dac8-45f2-840b-9e1205d4d1f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 25'])[1]/preceding::output[2]</value>
      <webElementGuid>014e5959-dcef-4430-b113-cfa94c32cde8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='95']/parent::*</value>
      <webElementGuid>a97b4a22-3e21-425e-93e6-77e4736aff3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/output</value>
      <webElementGuid>d0f9b7e4-7ab9-4954-a59d-b7495ebf7083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//output[@id = 'rangeSuccess' and (text() = '95' or . = '95')]</value>
      <webElementGuid>120cfc0e-2c81-44cf-96b3-37cbe49db9ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
