<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>output_91</name>
   <tag></tag>
   <elementGuidId>f248e73c-548c-45ae-956e-dd52d837ca59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//output[@id='rangeSuccess']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rangeSuccess</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>output</value>
      <webElementGuid>29fb9baa-75a6-4704-afab-1b1dcc68388c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rangeSuccess</value>
      <webElementGuid>46ab8065-b527-4201-b4c6-6fa013b0a3ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>91</value>
      <webElementGuid>544d6277-a1f4-4041-9e0b-51a27059ea2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rangeSuccess&quot;)</value>
      <webElementGuid>a010259d-075d-4381-bc57-4c1d1e9b9eb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//output[@id='rangeSuccess']</value>
      <webElementGuid>44b6fc8f-e796-4957-a5a7-0afa99897d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slider3']/div/output</value>
      <webElementGuid>2b89e2fa-0304-4221-bd30-035bc5187764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 15'])[1]/following::output[1]</value>
      <webElementGuid>b5e51df7-9958-4b88-b68d-1e89681650ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 20'])[1]/following::output[2]</value>
      <webElementGuid>be8dc356-05c8-426a-a391-203bc43f6d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 50'])[1]/preceding::output[1]</value>
      <webElementGuid>94477a1e-b151-459e-b848-3abf2040155a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 25'])[1]/preceding::output[2]</value>
      <webElementGuid>105fc132-e699-4c5c-b2ef-190563739dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='91']/parent::*</value>
      <webElementGuid>288fefc0-a02a-4372-9b0c-638a2a2a797f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/output</value>
      <webElementGuid>fa486863-08fa-4ff4-8c96-d8b9b1e4bd2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//output[@id = 'rangeSuccess' and (text() = '91' or . = '91')]</value>
      <webElementGuid>95708f5d-d457-4472-b457-28ad01f88729</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
