<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>output_96</name>
   <tag></tag>
   <elementGuidId>40420d05-e931-432a-930e-ac571551571e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//output[@id='range']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#range</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>output</value>
      <webElementGuid>47b5a268-5d12-45eb-98f3-f2f0a20b039d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>range</value>
      <webElementGuid>da5b3acd-7af7-4073-adbf-7027ee126262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>96</value>
      <webElementGuid>4d08d3ac-b542-4340-8374-691eefad95e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;range&quot;)</value>
      <webElementGuid>f9afac65-e47f-4595-a77a-74d1dd09ba83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//output[@id='range']</value>
      <webElementGuid>76faf32f-7419-4544-b12e-4c279c50ea02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slider1']/div/output</value>
      <webElementGuid>be448b6c-e2c1-425f-9209-7c9a05652b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 5'])[1]/following::output[1]</value>
      <webElementGuid>c53a4a10-96df-4b1d-8844-07ae698ee6ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Slider Demo'])[1]/following::output[1]</value>
      <webElementGuid>6a425955-5578-4f85-a51c-97f202333eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 20'])[1]/preceding::output[1]</value>
      <webElementGuid>d85aa2b9-5828-4450-8bd2-7216f0beb74b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 15'])[1]/preceding::output[2]</value>
      <webElementGuid>e3bd8fc3-0b13-4060-96d8-e65118f5bb11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='96']/parent::*</value>
      <webElementGuid>476c56ff-59ed-4d10-a79f-c77be3251d6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//output</value>
      <webElementGuid>5eeec864-4ed6-4fa1-91e9-5179c6c051de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//output[@id = 'range' and (text() = '96' or . = '96')]</value>
      <webElementGuid>464bccb9-9e39-4db4-b718-43b08a2fb831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//output[@id='rangeSuccess']</value>
      <webElementGuid>0839e605-974b-443d-bc8c-542d555c62f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slider3']/div/output</value>
      <webElementGuid>3eb2f969-49cf-4fb0-acfd-c0c036c481b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 15'])[1]/following::output[1]</value>
      <webElementGuid>325aba59-a256-46a3-b675-962390575a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 20'])[1]/following::output[2]</value>
      <webElementGuid>e68eabef-c48f-42d3-abc3-69aeb33dc56a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 50'])[1]/preceding::output[1]</value>
      <webElementGuid>c92425e5-d380-4a97-b9ee-1eadd12c7b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default value 25'])[1]/preceding::output[2]</value>
      <webElementGuid>9d701878-6b58-47bc-a7d9-9329d584f27c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/output</value>
      <webElementGuid>1ebb759c-4127-4f98-8176-f621320c190c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//output[@id = 'rangeSuccess' and (text() = '96' or . = '96')]</value>
      <webElementGuid>3713ec08-a42e-4a66-ba71-9ecc4518dde4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
