<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Selenium Testing</name>
   <tag></tag>
   <elementGuidId>8f077150-57ad-43f9-b8a7-919c90c1a740</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__docusaurus_skipToContent_fallback']/div/main/div/div/div/div/article/div/div[3]/a/div/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>fda06d3a-3e91-4add-8f7f-8c0792c5a72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selenium Testing</value>
      <webElementGuid>ce5d3406-2084-48a0-91da-c2f84071a3b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__docusaurus_skipToContent_fallback&quot;)/div[@class=&quot;docPage__5DB&quot;]/main[@class=&quot;docMainContainer_gTbr&quot;]/div[@class=&quot;container padding-top--md padding-bottom--lg&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;docItemContainer_Djhp&quot;]/article[1]/div[@class=&quot;theme-doc-markdown markdown&quot;]/div[@class=&quot;support_main&quot;]/a[1]/div[@class=&quot;support_inners&quot;]/h3[1]</value>
      <webElementGuid>b073eb4f-33ba-4ad2-af20-b3827bc34eca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__docusaurus_skipToContent_fallback']/div/main/div/div/div/div/article/div/div[3]/a/div/h3</value>
      <webElementGuid>25218885-08e5-40a9-8539-420ee4a8017d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/following::h3[1]</value>
      <webElementGuid>8b86c957-7b6c-4114-907f-f617fb60232a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cypress Testing'])[2]/preceding::h3[1]</value>
      <webElementGuid>a9f4cef1-310a-40d5-b6bc-f9daca4b98da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Playwright Testing'])[2]/preceding::h3[2]</value>
      <webElementGuid>d0c68ac4-02d7-4632-88e7-b12c9e0e2cc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>852ed11b-95d2-4596-a1a6-352c4f8cfaba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Selenium Testing' or . = 'Selenium Testing')]</value>
      <webElementGuid>a31ed61c-7b1a-42ae-a19a-abe510bfceee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
