<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Documentation</name>
   <tag></tag>
   <elementGuidId>53b4a4d9-53f3-4cd9-adb7-5878612b4bb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/nav/div/div/div[2]/div/div/div/div[4]/div/div/div/div/div/div[2]/ul/li[2]/a/div[2]/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>3d6e46d7-91dc-4968-afaa-42d6bfbf78cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-size-18 font-medium text-ltBlack-50 tracking-normal</value>
      <webElementGuid>2c50be90-c343-45c1-b2cf-bd1cf9dec2a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Documentation</value>
      <webElementGuid>04a95d81-7d64-4589-a12b-a6d2d4ae726b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/nav[@class=&quot;container&quot;]/div[@class=&quot;px-2 desktop:py-15&quot;]/div[@class=&quot;flex -mx-2 items-center desktop:block&quot;]/div[@class=&quot;header__menu px-2 desktop:w-full&quot;]/div[@class=&quot;desktop:mt-10 desktop:text-left desktop:hidden&quot;]/div[@class=&quot;flex items-center desktop:block&quot;]/div[@class=&quot;w-7/12 desktop:w-full header__menu__items&quot;]/div[@class=&quot;inline-block dropdown desktop:block resource-dropdown dropdown_menu&quot;]/div[@class=&quot;text-left dropdown-menu resource-dropdown-menu bg-white p-0 absolute top-auto left-0 rounded hasPointer desktop:static desktop:z-50&quot;]/div[@class=&quot;table__main&quot;]/div[@class=&quot;table w-full desktop:block&quot;]/div[@class=&quot;table-cell w-8/12 pb-20 desktop:block desktop:w-full&quot;]/div[@class=&quot;table w-full desktop:block&quot;]/div[@class=&quot;table-cell w-1/2 dropdowm-section desktop:w-full desktop:block&quot;]/ul[@class=&quot;header_inner header-icon&quot;]/li[2]/a[@class=&quot;flex&quot;]/div[@class=&quot;ml-26&quot;]/h3[@class=&quot;text-size-18 font-medium text-ltBlack-50 tracking-normal&quot;]</value>
      <webElementGuid>69b53d42-a46b-4080-a00d-e9d82a0e0ef6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/nav/div/div/div[2]/div/div/div/div[4]/div/div/div/div/div/div[2]/ul/li[2]/a/div[2]/h3</value>
      <webElementGuid>b0d8a0c3-3865-4e86-93f3-160382955ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Changelog'])[1]/following::h3[1]</value>
      <webElementGuid>f11bb26d-0ac8-421d-86c9-28b7d0e5dc53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guides'])[1]/following::h3[2]</value>
      <webElementGuid>ff1282d4-8151-4615-a6fd-b6d220f25c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API'])[2]/preceding::h3[1]</value>
      <webElementGuid>ef68271d-57cb-4d14-831f-b9074d7bb7a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GitHub Repositories'])[1]/preceding::h3[2]</value>
      <webElementGuid>d281f709-644c-4a0e-9e4c-ffc4b325c219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div[2]/ul/li[2]/a/div[2]/h3</value>
      <webElementGuid>87be8a95-3cb0-4da7-82f2-c191aef50b56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Documentation' or . = 'Documentation')]</value>
      <webElementGuid>f0350b23-f8e0-4e6f-9faf-eed6882bed28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
