<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Every month_os</name>
   <tag></tag>
   <elementGuidId>07bdf58e-fce8-46b1-9866-8ffd27fe1d12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='month']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#month</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2d96c08-cb8f-4dfe-975f-a2cbe3ffb15b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>3ca716d5-1543-43d8-ade9-3ffbf8ec2123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>os</value>
      <webElementGuid>fc95fe0c-738b-4dd4-ab7b-01992a8c56b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>month</value>
      <webElementGuid>a95267e0-a85f-458d-b5ae-4e47ac0daa25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-3</value>
      <webElementGuid>8fa91a45-cd2f-498b-9766-ff7ff07e28a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Every month</value>
      <webElementGuid>a4ea333a-4878-4aed-b3f5-db92eb1e6f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;month&quot;)</value>
      <webElementGuid>28fa27d0-ecbd-45f0-9469-62fc23121c6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='month']</value>
      <webElementGuid>738572b6-e535-4dc1-ad4e-f37dfef9e44c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[2]/div/div/div/p/label/input</value>
      <webElementGuid>0e06d795-46e8-498e-bc6f-24b7fe80e0ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>6d6f9cb9-11b9-48fe-871e-b834002ff1e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'os' and @id = 'month']</value>
      <webElementGuid>cbdc0456-c2b1-4ce6-b0fc-040002ef79df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
