<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Customer service_customer-service</name>
   <tag></tag>
   <elementGuidId>76921391-5df5-4215-8cd7-93835cbf113e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customer-service']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#customer-service</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6744084f-2c76-424a-8b5f-62b734294acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>88b54e80-a59e-43f8-a6f4-e7e41cb1da96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer-service</value>
      <webElementGuid>c896f588-d91f-4452-bde0-51d1c1c3096a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer-service</value>
      <webElementGuid>3a09b32b-0063-4faf-9239-a7d5874d06ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-10</value>
      <webElementGuid>89675db5-b987-44ff-926c-cf5bb5b0a9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer-service&quot;)</value>
      <webElementGuid>1e91d5b5-30a6-48c3-a0ca-cc5d529be1ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customer-service']</value>
      <webElementGuid>6599d9d8-ab0d-4bd6-b82d-03e6cd7639cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[2]/div/div/div[2]/p/label/input</value>
      <webElementGuid>17d612cd-549b-4df0-9f4f-adcedf6441fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p/label/input</value>
      <webElementGuid>2216d414-a3f9-4c20-94b1-96d14927036a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'customer-service' and @id = 'customer-service']</value>
      <webElementGuid>845341c5-2b9b-414d-9995-523697c4bc49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
