<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Your Email_email</name>
   <tag></tag>
   <elementGuidId>b21e83d7-1ffa-4951-8201-b5e1a1389a01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='developer-name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#developer-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68ace32b-a777-487a-80c1-9490ddbe7669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>developer-name</value>
      <webElementGuid>841ec19c-1e82-415b-bfbe-363b59d0391f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>81868671-9bba-4b8f-99af-22d8deabdb29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>2706665f-d765-4e33-9b9b-15b1d1197c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border border-black text-size-14 py-4 px-8 rounded</value>
      <webElementGuid>6be0f31d-0ec3-485a-b15b-d2dd6450a768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;developer-name&quot;)</value>
      <webElementGuid>89a67a6a-55da-4067-b96e-dc6b896d0cbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='developer-name']</value>
      <webElementGuid>4dd2344d-0c48-4758-bb37-c2af3f9a65e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[2]/div/div/form/input</value>
      <webElementGuid>a5cae156-f324-4464-a252-bb0206194331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/form/input</value>
      <webElementGuid>7ea7822b-f725-4b86-9252-82045225fb10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'developer-name' and @name = 'email' and @type = 'email']</value>
      <webElementGuid>c9acc8f0-f0f1-4414-976f-0ccc0ed0c949</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
