<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_I have made an eCommerce purchase in _ebb0b9</name>
   <tag></tag>
   <elementGuidId>e18344bf-f851-4fcb-bdf9-25b8f016e3d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tried-ecom']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tried-ecom</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>459c5bed-9e64-4eff-a5b8-51690987e719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>07ff465d-420d-4a96-a1e3-c6664f03e1c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tried-ecom</value>
      <webElementGuid>2426facd-aed9-425e-a39f-f19e15a28ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tried-ecom</value>
      <webElementGuid>88e46579-9af1-4597-a5d8-7d911837ea1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-10</value>
      <webElementGuid>645c42a0-70a5-48e2-b025-bd746922c813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tried-ecom&quot;)</value>
      <webElementGuid>faabc840-16fe-4e82-a994-fd37edc94841</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tried-ecom']</value>
      <webElementGuid>97fa24e6-2e58-466a-997d-d3b49c9ad954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tried-section']/label/input</value>
      <webElementGuid>792ad05b-963e-4c1e-b738-0471730890aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/label/input</value>
      <webElementGuid>afed42e4-3a1b-4ed1-a183-7fcecd815211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'tried-ecom' and @id = 'tried-ecom']</value>
      <webElementGuid>13bf1c28-b988-4f42-91a8-ea3b173a4288</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
