<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_upload image</name>
   <tag></tag>
   <elementGuidId>52d73327-eb29-49b9-8403-b9a5b20abcfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='img']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>fd21e18f-b981-4bf7-9ee0-262b8d168c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>0eec551b-6f89-4f80-a5a4-a56f4a545619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6d38bf8a-25c3-49cd-89d9-199152a92b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selenium__btn py-5 px-10 cursor-pointer font-bold capitalize border-2 border-gray-80 rounded-lg</value>
      <webElementGuid>c971d8a2-bbe4-4c6a-b713-cc8a7fbcb931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> upload image</value>
      <webElementGuid>d5f3e9b6-f468-4ac1-aba7-58bea3eb72c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img&quot;)</value>
      <webElementGuid>302eab23-115f-4644-aaaf-41efaf1fdf71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='img']</value>
      <webElementGuid>724a3ca9-119e-464f-97ed-beae56fef70e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[2]/div/div/div[4]/div[3]/div/form/label</value>
      <webElementGuid>b6561fd6-18a0-49fc-a53b-8d93179fbc20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please upload your file here:'])[1]/following::label[1]</value>
      <webElementGuid>a852dbdd-6a9c-4781-9443-72421255cddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::label[1]</value>
      <webElementGuid>9285104d-46e9-4426-8a12-715017440dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::label[1]</value>
      <webElementGuid>ce07d6b8-eb4b-44a4-96d2-c6c805e555c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='upload image']/parent::*</value>
      <webElementGuid>fd24e69c-b625-495f-8c48-c4aea8dba8cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/label</value>
      <webElementGuid>ec0aea31-e5c0-4463-ba95-ec96f1d38dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'img' and (text() = ' upload image' or . = ' upload image')]</value>
      <webElementGuid>cb77e953-6234-4ff5-b602-11053841d810</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
