<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Credit or Debit cardWalletsCash on delivery</name>
   <tag></tag>
   <elementGuidId>b99902ba-f753-4049-b699-3d3882c353cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='preferred-payment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#preferred-payment</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>11683818-a2fa-419c-ad46-5ae9518b3c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>preferred-payment</value>
      <webElementGuid>ca4ac2aa-c5da-41c1-b369-730d3225bb34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>preferred-payment</value>
      <webElementGuid>092c2d60-a0fb-42c3-bc50-9072092630ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-black font-medium text-size-14 border border-black w-7/12 bg-white rounded</value>
      <webElementGuid>dad0e494-d59f-4618-8267-9f47e33de33e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Credit or Debit cardWalletsCash on delivery</value>
      <webElementGuid>42aeec82-9756-4f78-a4b8-66fe0c39c632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;preferred-payment&quot;)</value>
      <webElementGuid>d12fda91-db76-4f65-ac66-7316f8e3bc96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='preferred-payment']</value>
      <webElementGuid>73211392-b4ac-49e5-940a-3f4af6372ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[2]/div/div/div[3]/select</value>
      <webElementGuid>ce8d1992-f375-4001-bac0-313fb3e12958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What mode of payment do you prefer usually?'])[1]/following::select[1]</value>
      <webElementGuid>e9e5bdc4-abd9-45bc-a933-0bb688f9dc3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Others'])[1]/following::select[1]</value>
      <webElementGuid>2ec0e79a-554e-4c6f-895e-1125a7672bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I have made an eCommerce purchase in the last 1 year'])[1]/preceding::select[1]</value>
      <webElementGuid>f71819aa-e221-449e-a8c7-dea083eea8cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>380c7493-ae61-4231-9c65-c29911a5956f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'preferred-payment' and @name = 'preferred-payment' and (text() = 'Credit or Debit cardWalletsCash on delivery' or . = 'Credit or Debit cardWalletsCash on delivery')]</value>
      <webElementGuid>38054388-1aa7-447e-8960-e5f75dce27fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
