<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LinkedIn_s</name>
   <tag></tag>
   <elementGuidId>3a37bffe-c1f2-4623-8a0a-d0beee8955ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;s&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='s']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81eee2f6-3fee-41ff-8cab-2ef7aee90c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3df54f05-97eb-4e4d-bd7f-ceb99bdc7df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>fc58124f-2086-4c3a-a6ce-72429734afed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>266e6f0d-c4d6-49ab-8619-8de805930a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>a5393707-5333-4ab0-8e28-659d138202eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-5&quot;)/form[@class=&quot;searchform&quot;]/input[@class=&quot;s&quot;]</value>
      <webElementGuid>c3a88ada-1400-4642-8517-b0398aae1e85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='s']</value>
      <webElementGuid>6daed825-4314-4b17-9dfa-24796250a9fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='search-5']/form/input</value>
      <webElementGuid>9ba6a3b5-c9be-4686-9ab8-fc0df198ed48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b0baf415-c568-4e9d-998d-0c60b5d4cc3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search' and @name = 's']</value>
      <webElementGuid>e9279930-06f8-4cc0-99e4-23ffbdc140bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
