<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LinkedIn_submit search_submit</name>
   <tag></tag>
   <elementGuidId>c5451900-3af0-4198-8104-0b6e5a7e1612</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.submit.search_submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='»']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92a18246-2a5e-4988-9aac-8e318d8dca95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8f41b71a-67bd-4965-9ef7-a5f3911c93ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit search_submit</value>
      <webElementGuid>835fb24e-5627-4bc6-ac78-68154959c024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>»</value>
      <webElementGuid>c1c1b539-83e4-4231-9876-0279a1deee5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-5&quot;)/form[@class=&quot;searchform&quot;]/input[@class=&quot;submit search_submit&quot;]</value>
      <webElementGuid>096853b6-8cb1-4014-bac6-a0a50e89cc17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='»']</value>
      <webElementGuid>18ec4fde-d25a-4abd-8cc9-156109c81393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='search-5']/form/input[2]</value>
      <webElementGuid>6d108196-2e6a-43c6-aeb5-c03e0a26b06b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>1cb853f6-c12b-45ad-9994-37fc721fa8f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>a583b340-f76b-418f-b871-f429fb5ed673</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
