<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Blog</name>
   <tag></tag>
   <elementGuidId>300a90c7-8e44-434a-85be-308cae3916f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/nav/div/div/div[2]/div/div/div/div[3]/div/div/div/div/div/div/ul/li/a/div[2]/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>65308d74-005e-42b0-8416-0ce810f965a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-size-18 font-medium text-ltBlack-50 tracking-normal</value>
      <webElementGuid>c84fc1bc-835f-49e3-82a8-1dc58c965812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Blog</value>
      <webElementGuid>7d1860c4-446c-42c9-9667-260caba8e3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/nav[@class=&quot;container&quot;]/div[@class=&quot;px-2 desktop:py-15&quot;]/div[@class=&quot;flex -mx-2 items-center desktop:block&quot;]/div[@class=&quot;header__menu px-2 desktop:w-full&quot;]/div[@class=&quot;desktop:mt-10 desktop:text-left desktop:hidden&quot;]/div[@class=&quot;flex items-center desktop:block&quot;]/div[@class=&quot;w-7/12 desktop:w-full header__menu__items&quot;]/div[@class=&quot;inline-block dropdown desktop:block resource-dropdown&quot;]/div[@class=&quot;text-left dropdown-menu resource-dropdown-menu bg-white p-0 absolute top-auto left-0 rounded hasPointer desktop:static desktop:z-50&quot;]/div[@class=&quot;table__main&quot;]/div[@class=&quot;table w-full desktop:block&quot;]/div[@class=&quot;table-cell w-8/12 pb-20 desktop:w-full desktop:block&quot;]/div[@class=&quot;table w-full desktop:block&quot;]/div[@class=&quot;table-cell w-1/2 dropdowm-section desktop:w-full desktop:block&quot;]/ul[@class=&quot;header_inner header-icon&quot;]/li[1]/a[@class=&quot;flex&quot;]/div[@class=&quot;ml-26&quot;]/h3[@class=&quot;text-size-18 font-medium text-ltBlack-50 tracking-normal&quot;]</value>
      <webElementGuid>8d248e90-ec55-4623-93f2-8764d98c97c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/nav/div/div/div[2]/div/div/div/div[3]/div/div/div/div/div/div/ul/li/a/div[2]/h3</value>
      <webElementGuid>bf0cbac5-19bc-4e4b-a0f0-660dd4c9a156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn'])[1]/following::h3[1]</value>
      <webElementGuid>d09d0662-703a-4d12-b926-1ccd534e64ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resources'])[1]/following::h3[1]</value>
      <webElementGuid>f436a921-a987-4bfd-ae2b-3f5af1d09f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Webinars'])[1]/preceding::h3[1]</value>
      <webElementGuid>30161a8a-10b4-49c1-bd88-1c1f3c8e6bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learning Hub'])[1]/preceding::h3[2]</value>
      <webElementGuid>01014da6-9a06-4b43-ac6c-391e8649c532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Blog']/parent::*</value>
      <webElementGuid>81b2dc17-2d46-4019-b7df-687fdab8fc5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/ul/li/a/div[2]/h3</value>
      <webElementGuid>1b116636-0795-476b-8487-5d1d6ebcfde3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Blog' or . = 'Blog')]</value>
      <webElementGuid>c7852a2d-9914-48ca-97c5-2357cc4bc483</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
