<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_0</name>
   <tag></tag>
   <elementGuidId>37795db2-e809-44bd-99b1-d9fcc24aac17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='free-product-price']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#free-product-price</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>a32adc15-24f8-4150-bfa5-498cabadcc78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xxl:text-size-48 text-size-44 font-bold mb-20 mt-6 text-black</value>
      <webElementGuid>b032840c-42cf-43b5-a02e-7299706fff11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>free-product-price</value>
      <webElementGuid>953d714b-c7e7-4303-aa67-c1ca569fbd3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$0</value>
      <webElementGuid>18b77ecb-fa3f-4f22-9136-5e854b8eb5a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar_and_product&quot;)/div[@class=&quot;w-10/12 desktop:w-full smtablet:mt-50&quot;]/div[@id=&quot;right_side&quot;]/div[@id=&quot;right_side_products&quot;]/div[@id=&quot;each_product&quot;]/div[@id=&quot;product_header&quot;]/div[@id=&quot;price_product&quot;]/div[@class=&quot;flex&quot;]/h2[@id=&quot;free-product-price&quot;]</value>
      <webElementGuid>c013f5e8-1fae-4b6a-8eb4-f90a21adf913</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='free-product-price']</value>
      <webElementGuid>f291211a-0255-4d7e-a1c5-0708a6c0c244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='price_product']/div[2]/h2</value>
      <webElementGuid>4be1a7d9-c9c9-4550-851b-f43b85ce9e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free'])[1]/following::h2[1]</value>
      <webElementGuid>149d2b52-b1d1-477c-9023-71414014473d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Smart UI'])[1]/following::h2[2]</value>
      <webElementGuid>dc5adf76-f55c-4a12-9164-2f32e0b33571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free Forever'])[1]/preceding::h2[1]</value>
      <webElementGuid>20b9c028-bd11-403a-8776-2a1b1dd7d442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Includes access to'])[1]/preceding::h2[1]</value>
      <webElementGuid>070e3513-73a3-4484-a0cb-4c75271f8d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$0']/parent::*</value>
      <webElementGuid>c865a30e-f0dd-4120-8cdc-7fa01792bf0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/h2</value>
      <webElementGuid>c94bf496-a928-4d5d-8a93-d87f9008d591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'free-product-price' and (text() = '$0' or . = '$0')]</value>
      <webElementGuid>e5432ec5-8506-4eaa-af60-8e236e807d9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
