<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_15</name>
   <tag></tag>
   <elementGuidId>a10de1da-6de0-426d-9a02-3f1afdb4dc63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='price_product']/div/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>9a5092f2-55b4-414e-8034-e1d70c8fd752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xxll:text-size-48 xxl:text-size-46 xlm:text-size-44 text-size-42 font-bold mb-20 mt-6 text-black</value>
      <webElementGuid>419df0c0-0111-433c-af09-e9d42c3eee80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$15</value>
      <webElementGuid>425e2e54-4e52-4014-a24b-62d93fc38774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar_and_product&quot;)/div[@class=&quot;w-10/12 desktop:w-full smtablet:mt-50&quot;]/div[@id=&quot;right_side&quot;]/div[@id=&quot;right_side_products&quot;]/div[@id=&quot;each_product&quot;]/div[@id=&quot;product_header&quot;]/div[@id=&quot;price_product&quot;]/div[@class=&quot;flex items-center&quot;]/h3[@class=&quot;xxll:text-size-48 xxl:text-size-46 xlm:text-size-44 text-size-42 font-bold mb-20 mt-6 text-black&quot;]</value>
      <webElementGuid>e0794b75-3ec3-446e-8b29-8890a2f1e074</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='price_product']/div/h3</value>
      <webElementGuid>383113e8-3025-4a63-a2fa-fa06f8a2b1d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Live'])[1]/following::h3[1]</value>
      <webElementGuid>7504b531-a03a-4aa0-a1ec-861003a922fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Live real time testing'])[1]/following::h3[1]</value>
      <webElementGuid>b412b289-a6d7-461f-b8ce-63cc31e6dca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/monthbilled annually'])[1]/preceding::h3[1]</value>
      <webElementGuid>fe668af4-71dc-49a6-af7c-0a411b584640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Plan'])[1]/preceding::h3[1]</value>
      <webElementGuid>4509f429-9ac0-4a2c-8cbf-13d483231b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$15']/parent::*</value>
      <webElementGuid>32adc75c-473e-41b3-94b1-1dec5eea155b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h3</value>
      <webElementGuid>c451f386-70e0-4bab-8fc1-a9248c97d216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = '$15' or . = '$15')]</value>
      <webElementGuid>146ee545-4be1-4be0-90fe-8d9fe21bc964</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
