<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Monthly</name>
   <tag></tag>
   <elementGuidId>0a6ccf8c-e33c-4e1b-be6e-6d5e1de1ec41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='monthly_annual_div']/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.p-10.px-15.text-size-16.text-black.inline-block.rounded-full.cursor-pointer.font-medium.border.border-gray-11</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8ee13a92-efb8-40d5-992f-ce514b9ce728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-10 px-15 text-size-16 text-black inline-block rounded-full cursor-pointer font-medium border border-gray-11</value>
      <webElementGuid>e21bf430-88ba-4ba7-afcc-6819d654225d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Monthly</value>
      <webElementGuid>5d91cc7a-5b65-4f87-acbd-bbc6b39d2688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;monthly_annual_div&quot;)/div[@class=&quot;lg:mt-0 mt-20 text-center&quot;]/div[@class=&quot;rounded-full overflow-hidden bg-gray-11 inline-block p-5&quot;]/span[@class=&quot;p-10 px-15 text-size-16 text-black inline-block rounded-full cursor-pointer font-medium border border-gray-11&quot;]</value>
      <webElementGuid>f69b53d9-8539-493b-92af-3e1adb431cb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='monthly_annual_div']/div/div/span</value>
      <webElementGuid>d9a5195e-0961-4b6b-affc-f14c5e234122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get The Unified Testing Platform'])[1]/following::span[1]</value>
      <webElementGuid>e6db87dd-7295-4606-a267-e0ebfc3a5a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Started Free'])[1]/following::span[1]</value>
      <webElementGuid>01c2fb9a-c344-4334-a893-d6bb2f0b7bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Annual (Save upto 20%)'])[1]/preceding::span[1]</value>
      <webElementGuid>eb9ab81d-0247-4cf2-9552-05a2308af492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manual Testing'])[1]/preceding::span[3]</value>
      <webElementGuid>aa1e4505-01f9-4ec5-9fd1-5196766281e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Monthly']/parent::*</value>
      <webElementGuid>75d53e06-774c-4876-afd3-2ad44b56e8a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>4b380d08-3364-4037-b881-ac32ad913f77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Monthly' or . = 'Monthly')]</value>
      <webElementGuid>f2128f0b-3c47-4b03-afe6-97dbc47c5af7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
